"""add contact request model

Revision ID: 07f67a145d53
Revises: 94e1f03da9e4
Create Date: 2024-05-26 16:12:40.705754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f67a145d53'
down_revision: Union[str, None] = '94e1f03da9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_requests_email'), 'contact_requests', ['email'], unique=False)
    op.create_index(op.f('ix_contact_requests_id'), 'contact_requests', ['id'], unique=False)
    op.create_index(op.f('ix_contact_requests_name'), 'contact_requests', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_name'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_email'), table_name='contact_requests')
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
